name: PersonalChest
version: 1.0.3
main: nl.rodey.personalchest.pchestMain
depend: [Spout]
commands:
   pchest:
      description: Register or unregister the Chest with these commands or check if registered.
      usage: /pchest [CREATE|REMOVE|INFO]